In [2]:
import numpy as np

Mathematical operations

In [3]:
a1=np.array([1,6,8,6,5,4])
a1

array([1, 6, 8, 6, 5, 4])

In [4]:
a2=np.array([2,5,7,9,4,2])
a2

array([2, 5, 7, 9, 4, 2])

In [5]:
a1+a2

array([ 3, 11, 15, 15,  9,  6])

In [6]:
a=(2,34,567,890,2)
b=(1,2,34,5,67)

a+b

(2, 34, 567, 890, 2, 1, 2, 34, 5, 67)

In [7]:
a1-a2

array([-1,  1,  1, -3,  1,  2])

In [8]:
a1*a2

array([ 2, 30, 56, 54, 20,  8])

In [9]:
a1/a2

array([0.5       , 1.2       , 1.14285714, 0.66666667, 1.25      ,
       2.        ])

In [10]:
ans=a1**2
ans

array([ 1, 36, 64, 36, 25, 16])

In [11]:
np.sqrt(ans)

array([1., 6., 8., 6., 5., 4.])

In [12]:
a3=np.array([1.2,1.5,2.6,4.2,6.5])
a3

array([1.2, 1.5, 2.6, 4.2, 6.5])

In [13]:
np.floor(a3)

array([1., 1., 2., 4., 6.])

In [14]:
np.ceil(a3)

array([2., 2., 3., 5., 7.])

In [15]:
np.round(a3)

array([1., 2., 3., 4., 6.])

Combining Array


In [16]:
a1

array([1, 6, 8, 6, 5, 4])

In [17]:
a2

array([2, 5, 7, 9, 4, 2])

In [18]:
np.concatenate((a1,a2))

array([1, 6, 8, 6, 5, 4, 2, 5, 7, 9, 4, 2])

In [19]:
arr1=np.array([[3,4,5],[2,3,9],[2,8,0]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
arr1

array([[3, 4, 5],
       [2, 3, 9],
       [2, 8, 0]])

In [21]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.vstack((arr1,arr2))

array([[3, 4, 5],
       [2, 3, 9],
       [2, 8, 0],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.hstack((arr1,arr2))

array([[3, 4, 5, 1, 2, 3],
       [2, 3, 9, 4, 5, 6],
       [2, 8, 0, 7, 8, 9]])

In [24]:
arr1.flatten()

array([3, 4, 5, 2, 3, 9, 2, 8, 0])

In [25]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Splitting Array

In [26]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [27]:
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [28]:
arr2=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [29]:
np.hsplit(arr2,3)

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

In [30]:
np.vsplit(arr2,2)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

Searching in Array

In [31]:
a1

array([1, 6, 8, 6, 5, 4])

In [32]:
np.where(a1==8)

(array([2]),)

In [33]:
a3=np.array([1,3,5,6,3,7])
a3

array([1, 3, 5, 6, 3, 7])

In [34]:
np.where(a3==3)

(array([1, 4]),)

In [35]:
np.where(a3>3)

(array([2, 3, 5]),)

In [36]:
arr1

array([[3, 4, 5],
       [2, 3, 9],
       [2, 8, 0]])

In [37]:
np.where(arr1==5)

(array([0]), array([2]))

In [38]:
arr3=np.array([[1,2,3],[2,5,7],[4,5,2]])
arr3

array([[1, 2, 3],
       [2, 5, 7],
       [4, 5, 2]])

In [39]:
np.where(arr3==2)

(array([0, 1, 2]), array([1, 0, 2]))

Sorting of Array

In [40]:
a1

array([1, 6, 8, 6, 5, 4])

In [41]:
np.sort(a1)

array([1, 4, 5, 6, 6, 8])

In [ ]:
np.argsort(a1) 

array([0, 5, 4, 1, 3, 2])

In [43]:
arr3

array([[1, 2, 3],
       [2, 5, 7],
       [4, 5, 2]])

In [44]:
np.sort(arr3)

array([[1, 2, 3],
       [2, 5, 7],
       [2, 4, 5]])

In [45]:
np.argsort(arr3)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]])

In [ ]:
np.sort(arr3)[:, ::-1]   # Row-wise

array([[3, 2, 1],
       [7, 5, 2],
       [5, 4, 2]])

In [ ]:
np.sort(arr3, axis=0)[::-1, :]   # Column-wise

array([[4, 5, 7],
       [2, 5, 3],
       [1, 2, 2]])

Aggregating & Statisticol Functions

In [48]:
a1

array([1, 6, 8, 6, 5, 4])

In [49]:
np.sum(a1)

np.int64(30)

In [50]:
np.mean(a1)

np.float64(5.0)

In [51]:
np.median(a1)

np.float64(5.5)

In [52]:
np.max(a1)

np.int64(8)

In [53]:
np.min(a1)

np.int64(1)

In [54]:
np.std(a1)

np.float64(2.160246899469287)

In [55]:
np.var(a1)

np.float64(4.666666666666667)

In [56]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
np.sum(arr4)

np.int64(45)

In [58]:
np.sum(arr4,axis=1)

array([ 6, 15, 24])

In [59]:
np.sum(arr4,axis=0)

array([12, 15, 18])