Boolean Indexing (Filtering Array)

In [235]:
import numpy as np

In [236]:
arr=np.array([10,15,20,25,30])
arr[True]

array([[10, 15, 20, 25, 30]])

In [237]:
l=[True,False,True,True,False]
l

[True, False, True, True, False]

In [238]:
arr[l]  

array([10, 20, 25])

In [239]:
arr

array([10, 15, 20, 25, 30])

In [240]:
l2=(arr%2==0)
l2

array([ True, False,  True, False,  True])

In [241]:
arr[l2]

array([10, 20, 30])

In [242]:
arr[arr%2==0]

array([10, 20, 30])

In [243]:
age=np.array([42,18,22,13,16])
age

array([42, 18, 22, 13, 16])

In [244]:
age[age>18]

array([42, 22])

In [245]:
age[age==22]

array([22])

In [246]:
a2=np.array([[3,5,7],[1,2,9],[6,4,2]])
a2

array([[3, 5, 7],
       [1, 2, 9],
       [6, 4, 2]])

In [247]:
l1=[True,False,True]
l1

[True, False, True]

In [248]:
a2[l1]

array([[3, 5, 7],
       [6, 4, 2]])

Boolean Mask (Masking Array)

In [249]:
arr

array([10, 15, 20, 25, 30])

In [250]:
l

[True, False, True, True, False]

In [251]:
print(np.ma.array(arr,mask=l))

[-- 15 -- -- 30]


In [252]:
odd_number=np.ma.array(arr,mask=arr%2==0)
print(odd_number)

[-- 15 -- 25 --]


Reshaping Array

In [253]:
a2

array([[3, 5, 7],
       [1, 2, 9],
       [6, 4, 2]])

In [254]:
a2.flatten()

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [255]:
a2.reshape(-1)

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [256]:
a2.ravel()

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [257]:
a1d=np.arange(0,12)

In [258]:
a1d.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [259]:
a1d.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [260]:
a1d.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [261]:
a1d.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [262]:
a1d.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [263]:
a1d.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

1.Scalar Broadcasting

In [264]:
arr

array([10, 15, 20, 25, 30])

In [266]:
s1=[3]
s2=5
s3=np.array([6])

In [267]:
arr+s2

array([15, 20, 25, 30, 35])

In [268]:
arr+s1

array([13, 18, 23, 28, 33])

In [269]:
arr+8

array([18, 23, 28, 33, 38])

In [270]:
arr+s3

array([16, 21, 26, 31, 36])

2.Vector Broadcasting

1.Row-vactor
2.Column_vactor

1.Row_Vactor

In [271]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([10,20,30])

In [272]:
print(a1+a2)

[[11 22 33]
 [14 25 36]]


2.Column-Vactor

In [277]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([10,20]).reshape(-1,1)

In [278]:
print(a1+a2)

[[11 12 13]
 [24 25 26]]


3.Matrix Broadcasting

In [279]:
a1=np.array([[1],[2]])
a2=np.array([[10,20,30]])

print(a1)
print()
print(a2)
print()

a3=a1+a2
print(a3)

[[1]
 [2]]

[[10 20 30]]

[[11 21 31]
 [12 22 32]]
