In [70]:
import numpy as np

In [71]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

Creating An Array

In [72]:
l=[1,4,6,8]
print(l)

[1, 4, 6, 8]


In [73]:
arr=np.array(l)
print(arr)

[1 4 6 8]


In [74]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [77]:
a=np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [78]:
a2=np.ones(4)
a2

array([1., 1., 1., 1.])

In [79]:
a3=np.eye(3)
a3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
ar1=np.zeros((3,3))
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
ar2=np.ones((3,3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
ar3=np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
ar4=np.arange(1,11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
ar5=np.arange(1,11,2)
ar5

array([1, 3, 5, 7, 9])

In [85]:
ar6=np.linspace(1,10,5)
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [86]:
ar7=np.full(5,3)
ar7

array([3, 3, 3, 3, 3])

In [87]:
ar8=np.full((3,3),8)
ar8

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [88]:
r1=np.random.rand(3,3)
r1

array([[0.2282791 , 0.1909431 , 0.83438037],
       [0.56235592, 0.96436659, 0.49783494],
       [0.0586856 , 0.32277485, 0.66333644]])

In [89]:
r2=np.random.rand(5)
r2

array([0.26129263, 0.16730419, 0.41758774, 0.96414305, 0.65408756])

In [90]:
r3=np.random.randint(5)
r3

3

In [91]:
r4=np.random.randint(3,10)
r4

4

In [92]:
r5=np.random.randint(3,10,5)
r5

array([6, 9, 8, 6, 7], dtype=int32)

In [93]:
r6=np.random.randint(3,10,(3,3))
r6

array([[4, 7, 3],
       [4, 8, 3],
       [5, 9, 5]], dtype=int32)

Indexing of Array:

In [94]:
arr=np.array(l)
arr

array([1, 4, 6, 8])

In [95]:
print(arr[0])

1


In [96]:
(arr[3])

np.int64(8)

In [97]:
(arr[-3])

np.int64(4)

In [98]:
(arr[-1])

np.int64(8)

In [99]:
a2=np.random.randint(1,10,(3,3))
a2

array([[9, 7, 9],
       [4, 8, 3],
       [4, 2, 9]], dtype=int32)

In [100]:
(a2[0][1])

np.int32(7)

In [101]:
(a2[2][0])

np.int32(4)

In [102]:
(a2[0,1])

np.int32(7)

In [103]:
(a2[1,2])

np.int32(3)

In [104]:
print(a2)

[[9 7 9]
 [4 8 3]
 [4 2 9]]


Slicing on Array : 

In [105]:
a=np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [106]:
a[0:3]

array([3, 4, 5])

In [107]:
a[-1:-5:-1]

array([9, 8, 7, 6])

In [108]:
a[2:6]

array([5, 6, 7, 8])

In [109]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [110]:
a[0:]

array([3, 4, 5, 6, 7, 8, 9])

In [111]:
a[0::1]

array([3, 4, 5, 6, 7, 8, 9])

In [112]:
a[0::2]

array([3, 5, 7, 9])

In [113]:
a[::]

array([3, 4, 5, 6, 7, 8, 9])

In [114]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3])

In [115]:
a2=np.random.randint(1,10,(3,3))
a2

array([[3, 1, 9],
       [7, 6, 9],
       [6, 1, 5]], dtype=int32)

In [116]:
a2[0:2,2]

array([9, 9], dtype=int32)

In [117]:
a2[0:,1]

array([1, 6, 1], dtype=int32)

In [118]:
a2[1,0:2]

array([7, 6], dtype=int32)

In [119]:
a2

array([[3, 1, 9],
       [7, 6, 9],
       [6, 1, 5]], dtype=int32)

In [120]:
a2[:,:]

array([[3, 1, 9],
       [7, 6, 9],
       [6, 1, 5]], dtype=int32)

In [121]:
a2[0:,1:]

array([[1, 9],
       [6, 9],
       [1, 5]], dtype=int32)

Shape,Size and Datatype of Array : 

In [122]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [123]:
print(a.shape)

(7,)


In [124]:
a2

array([[3, 1, 9],
       [7, 6, 9],
       [6, 1, 5]], dtype=int32)

In [125]:
print(a2.shape)

(3, 3)


In [126]:
print(a.size)

7


In [127]:
print(a2.size)

9


In [128]:
print(a.dtype)

int64


In [129]:
print(a2.dtype)

int32


Mathematical Operations on Array : 

In [130]:
a1=np.arange(11,20)
a2=np.arange(21,30)

In [131]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [132]:
a2

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [133]:
a1+a2

array([32, 34, 36, 38, 40, 42, 44, 46, 48])

In [134]:
a1*a2

array([231, 264, 299, 336, 375, 416, 459, 504, 551])

In [135]:
a3=np.array([16,81,223,4,6])
np.sort(a3)

array([  4,   6,  16,  81, 223])