In [7]:
import numpy as np

In [ ]:
dir(np)

Creating An Array

In [9]:
l=[1,4,6,8]
l

[1, 4, 6, 8]

In [10]:
l=[1,4,6,8]
print(l)

[1, 4, 6, 8]


In [11]:
import numpy as np

l = [1, 4, 6, 8]
arr = np.array(l)
print(arr)

[1 4 6 8]


In [12]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [79]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a3=np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [14]:
a4=np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
ar1=np.zeros((3,3))
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
ar2=np.ones((3,3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ar3=np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
ar4=np.arange(1,11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
ar5=np.arange(1,11,2)
ar5

array([1, 3, 5, 7, 9])

In [20]:
ar6=np.linspace(1,10,5)
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
arr7=np.full(5,3)
arr7

array([3, 3, 3, 3, 3])

In [22]:
arr8=np.full(7,4)
arr8

array([4, 4, 4, 4, 4, 4, 4])

In [ ]:
import numpy as np

In [ ]:
dir(np)

Creating An Array

In [ ]:
l=[1,4,6,8]
l

[1, 4, 6, 8]

In [ ]:
l=[1,4,6,8]
print(l)

[1, 4, 6, 8]


In [ ]:
import numpy as np

l = [1, 4, 6, 8]
arr = np.array(l)
print(arr)

[1 4 6 8]


In [ ]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a3=np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [ ]:
a4=np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ar1=np.zeros((3,3))
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ar2=np.ones((3,3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ar3=np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar4=np.arange(1,11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ar5=np.arange(1,11,2)
ar5

array([1, 3, 5, 7, 9])

In [ ]:
ar6=np.linspace(1,10,5)
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
arr7=np.full(5,3)
arr7

array([3, 3, 3, 3, 3])

In [ ]:
arr8=np.full(7,4)
arr8

array([4, 4, 4, 4, 4, 4, 4])

In [ ]:
arr9=np.full((3,3),9)
arr9

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
r1=np.random.rand(3,3)
r1

array([[0.19068857, 0.77068755, 0.93344913],
       [0.66439505, 0.81169329, 0.45582728],
       [0.08321819, 0.5187125 , 0.15571738]])

In [ ]:
r2=np.random.rand(5)
r2

array([0.91553981, 0.63240222, 0.39246454, 0.05332744, 0.48245943])

In [ ]:
r3=np.random.randint(5)
r3

1

In [ ]:
r4=np.random.randint(3,10)
r4

4

In [ ]:
r5=np.random.randint(3,10,5)
r5

array([9, 5, 4, 8, 9], dtype=int32)

In [ ]:
r6=np.random.randint(3,10,(3,3))
r6

array([[3, 3, 9],
       [4, 3, 6],
       [7, 3, 6]], dtype=int32)

In [ ]:
r7=np.random.randint(1,10,(4,4))
r7

array([[4, 9, 6, 3],
       [3, 7, 8, 7],
       [2, 4, 7, 2],
       [3, 7, 1, 3]], dtype=int32)

Indexing of Array

In [ ]:
import numpy as np

l = [1, 4, 6, 8, 5, 8, 9, 3]
arr = np.array(l)
print(arr)

[1 4 6 8 5 8 9 3]


In [ ]:
print(arr[0])

1


In [ ]:
print(arr[-1])

3


In [ ]:
print(arr[3])

8


In [ ]:
print(arr[5])

8


In [ ]:
print(arr[-2])

9


In [ ]:
a2=np.random.randint(1,10,(3,3))
a2

array([[3, 5, 3],
       [7, 7, 6],
       [7, 2, 5]], dtype=int32)

In [ ]:
print(a2[0][1])

5


In [ ]:
print(a2[2][0])

7


In [ ]:
print(a2[0][0])

3


In [ ]:
print(a2[0][1])

5


In [ ]:
print(a2)

[[3 5 3]
 [7 7 6]
 [7 2 5]]


In [ ]:
print(a2[0])

[3 5 3]


In [ ]:
print(a2[1])

[7 7 6]


In [ ]:
print(a2[2][1])

2


In [ ]:
print(a2[1][2])

6


Slicing of Array

In [ ]:
a=np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[0:3]

array([3, 4, 5])

In [ ]:
a[-1:-5:-1]

array([9, 8, 7, 6])

In [ ]:
a[2:6]

array([5, 6, 7, 8])

In [ ]:
a[0:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[0::1]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[0::2]

array([3, 5, 7, 9])

In [ ]:
a[0::3]

array([3, 6, 9])

In [ ]:
a[::]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3])

In [ ]:
a[::-2]

array([9, 7, 5, 3])

In [ ]:
a2=np.random.randint(1,10,(3,3))
a2

array([[9, 9, 9],
       [1, 7, 6],
       [2, 9, 9]], dtype=int32)

In [ ]:
a2[0:2,2]

array([9, 6], dtype=int32)

In [ ]:
a2[0:1,2]

array([9], dtype=int32)

In [ ]:
a2[0:,1]

array([9, 7, 9], dtype=int32)

In [ ]:
a2[1,0:2]

array([1, 7], dtype=int32)

In [ ]:
a2[:,:]

array([[9, 9, 9],
       [1, 7, 6],
       [2, 9, 9]], dtype=int32)

In [ ]:
a2[0:,1:]

array([[9, 9],
       [7, 6],
       [9, 9]], dtype=int32)

Shape,Size,and Datatype of Array

In [ ]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(a.shape)

(7,)


In [ ]:
a2

array([[9, 9, 9],
       [1, 7, 6],
       [2, 9, 9]], dtype=int32)

In [ ]:
print(a2.shape)

(3, 3)


In [ ]:
print(a2.size)

9


In [ ]:
print(a.size)

7


In [ ]:
print(a.dtype)

int64


In [ ]:
print(a2.dtype)

int32


mathematical operationson Array

In [ ]:
a1=np.arange(11,20)
a2=np.arange(5,14)

In [ ]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
a2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
a1+a2

array([16, 18, 20, 22, 24, 26, 28, 30, 32])

In [ ]:
a1*a2

array([ 55,  72,  91, 112, 135, 160, 187, 216, 247])

In [ ]:
a3=np.array([16,81,25,121,9])
np.sqrt(a3)

array([ 4.,  9.,  5., 11.,  3.])

In [23]:
arr9=np.full((3,3),9)
arr9

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [24]:
r1=np.random.rand(3,3)
r1

array([[0.19068857, 0.77068755, 0.93344913],
       [0.66439505, 0.81169329, 0.45582728],
       [0.08321819, 0.5187125 , 0.15571738]])

In [25]:
r2=np.random.rand(5)
r2

array([0.91553981, 0.63240222, 0.39246454, 0.05332744, 0.48245943])

In [26]:
r3=np.random.randint(5)
r3

1

In [27]:
r4=np.random.randint(3,10)
r4

4

In [28]:
r5=np.random.randint(3,10,5)
r5

array([9, 5, 4, 8, 9], dtype=int32)

In [29]:
r6=np.random.randint(3,10,(3,3))
r6

array([[3, 3, 9],
       [4, 3, 6],
       [7, 3, 6]], dtype=int32)

In [30]:
r7=np.random.randint(1,10,(4,4))
r7

array([[4, 9, 6, 3],
       [3, 7, 8, 7],
       [2, 4, 7, 2],
       [3, 7, 1, 3]], dtype=int32)

Indexing of Array

In [31]:
import numpy as np

l = [1, 4, 6, 8, 5, 8, 9, 3]
arr = np.array(l)
print(arr)

[1 4 6 8 5 8 9 3]


In [32]:
print(arr[0])

1


In [33]:
print(arr[-1])

3


In [34]:
print(arr[3])

8


In [35]:
print(arr[5])

8


In [36]:
print(arr[-2])

9


In [37]:
a2=np.random.randint(1,10,(3,3))
a2

array([[3, 5, 3],
       [7, 7, 6],
       [7, 2, 5]], dtype=int32)

In [38]:
print(a2[0][1])

5


In [39]:
print(a2[2][0])

7


In [40]:
print(a2[0][0])

3


In [41]:
print(a2[0][1])

5


In [42]:
print(a2)

[[3 5 3]
 [7 7 6]
 [7 2 5]]


In [43]:
print(a2[0])

[3 5 3]


In [44]:
print(a2[1])

[7 7 6]


In [45]:
print(a2[2][1])

2


In [46]:
print(a2[1][2])

6


Slicing of Array

In [47]:
a=np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [48]:
a[0:3]

array([3, 4, 5])

In [49]:
a[-1:-5:-1]

array([9, 8, 7, 6])

In [50]:
a[2:6]

array([5, 6, 7, 8])

In [51]:
a[0:]

array([3, 4, 5, 6, 7, 8, 9])

In [52]:
a[0::1]

array([3, 4, 5, 6, 7, 8, 9])

In [53]:
a[0::2]

array([3, 5, 7, 9])

In [54]:
a[0::3]

array([3, 6, 9])

In [55]:
a[::]

array([3, 4, 5, 6, 7, 8, 9])

In [56]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3])

In [57]:
a[::-2]

array([9, 7, 5, 3])

In [58]:
a2=np.random.randint(1,10,(3,3))
a2

array([[9, 9, 9],
       [1, 7, 6],
       [2, 9, 9]], dtype=int32)

In [59]:
a2[0:2,2]

array([9, 6], dtype=int32)

In [60]:
a2[0:1,2]

array([9], dtype=int32)

In [61]:
a2[0:,1]

array([9, 7, 9], dtype=int32)

In [62]:
a2[1,0:2]

array([1, 7], dtype=int32)

In [63]:
a2[:,:]

array([[9, 9, 9],
       [1, 7, 6],
       [2, 9, 9]], dtype=int32)

In [64]:
a2[0:,1:]

array([[9, 9],
       [7, 6],
       [9, 9]], dtype=int32)

Shape,Size,and Datatype of Array

In [65]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [66]:
print(a.shape)

(7,)


In [67]:
a2

array([[9, 9, 9],
       [1, 7, 6],
       [2, 9, 9]], dtype=int32)

In [68]:
print(a2.shape)

(3, 3)


In [69]:
print(a2.size)

9


In [70]:
print(a.size)

7


In [71]:
print(a.dtype)

int64


In [72]:
print(a2.dtype)

int32


mathematical operationson Array

In [73]:
a1=np.arange(11,20)
a2=np.arange(5,14)

In [74]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [75]:
a2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [76]:
a1+a2

array([16, 18, 20, 22, 24, 26, 28, 30, 32])

In [77]:
a1*a2

array([ 55,  72,  91, 112, 135, 160, 187, 216, 247])

In [78]:
a3=np.array([16,81,25,121,9])
np.sqrt(a3)

array([ 4.,  9.,  5., 11.,  3.])