In [ ]:
import numpy as np

In [ ]:
dir(np)

Creating An Array

In [3]:
l=[1,4,6,8]
l

[1, 4, 6, 8]

In [4]:
l=[1,4,6,8]
print(l)

[1, 4, 6, 8]


In [9]:
import numpy as np

l = [1, 4, 6, 8]
arr = np.array(l)
print(arr)

[1 4 6 8]


In [4]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [5]:
a3=np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [6]:
a4=np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
ar1=np.zeros((3,3))
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
ar2=np.ones((3,3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
ar3=np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
ar4=np.arange(1,11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
ar5=np.arange(1,11,2)
ar5

array([1, 3, 5, 7, 9])

In [12]:
ar6=np.linspace(1,10,5)
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
arr7=np.full(5,3)
arr7

array([3, 3, 3, 3, 3])

In [14]:
arr8=np.full(7,4)
arr8

array([4, 4, 4, 4, 4, 4, 4])

In [15]:
arr9=np.full((3,3),9)
arr9

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [16]:
r1=np.random.rand(3,3)
r1

array([[0.20929732, 0.71821398, 0.22749292],
       [0.61079883, 0.59738903, 0.19103838],
       [0.59998066, 0.81996508, 0.18161759]])

In [17]:
r2=np.random.rand(5)
r2

array([0.83314031, 0.84152391, 0.90002199, 0.79945136, 0.90443051])

In [18]:
r3=np.random.randint(5)
r3

0

In [19]:
r4=np.random.randint(3,10)
r4

7

In [20]:
r5=np.random.randint(3,10,5)
r5

array([7, 9, 8, 7, 7], dtype=int32)

In [21]:
r6=np.random.randint(3,10,(3,3))
r6

array([[5, 8, 8],
       [7, 9, 4],
       [6, 6, 6]], dtype=int32)

In [22]:
r7=np.random.randint(1,10,(4,4))
r7

array([[6, 6, 4, 5],
       [6, 1, 3, 5],
       [7, 8, 6, 5],
       [2, 6, 9, 1]], dtype=int32)

Indexing of Array

In [1]:
import numpy as np

l = [1, 4, 6, 8, 5, 8, 9, 3]
arr = np.array(l)
print(arr)

[1 4 6 8 5 8 9 3]


In [3]:
print(arr[0])

1


In [4]:
print(arr[-1])

3


In [5]:
print(arr[3])

8


In [6]:
print(arr[5])

8


In [7]:
print(arr[-2])

9


In [8]:
a2=np.random.randint(1,10,(3,3))
a2

array([[3, 7, 2],
       [6, 6, 9],
       [6, 9, 3]], dtype=int32)

In [12]:
print(a2[0][1])

7


In [13]:
print(a2[2][0])

6


In [14]:
print(a2[0][0])

3


In [15]:
print(a2[0][1])

7


In [17]:
print(a2)

[[3 7 2]
 [6 6 9]
 [6 9 3]]


In [18]:
print(a2[0])

[3 7 2]


In [19]:
print(a2[1])

[6 6 9]


In [21]:
print(a2[2][1])

9


In [24]:
print(a2[1][2])

9


Slicing of Array

In [25]:
a=np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
a[0:3]

array([3, 4, 5])

In [27]:
a[-1:-5:-1]

array([9, 8, 7, 6])

In [28]:
a[2:6]

array([5, 6, 7, 8])

In [29]:
a[0:]

array([3, 4, 5, 6, 7, 8, 9])

In [30]:
a[0::1]

array([3, 4, 5, 6, 7, 8, 9])

In [31]:
a[0::2]

array([3, 5, 7, 9])

In [32]:
a[0::3]

array([3, 6, 9])

In [33]:
a[::]

array([3, 4, 5, 6, 7, 8, 9])

In [34]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3])

In [35]:
a[::-2]

array([9, 7, 5, 3])

In [36]:
a2=np.random.randint(1,10,(3,3))
a2

array([[1, 8, 1],
       [8, 4, 2],
       [5, 6, 2]], dtype=int32)

In [37]:
a2[0:2,2]

array([1, 2], dtype=int32)

In [38]:
a2[0:1,1]

array([8], dtype=int32)

In [41]:
a2[0:,1]

array([8, 4, 6], dtype=int32)