In [2]:
import numpy as np

In [3]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

Creating An Array

In [4]:
l=[1,4,6,8]
l

[1, 4, 6, 8]

In [5]:
l=[1,4,6,8]
print(l)

[1, 4, 6, 8]


In [6]:
import numpy as np

l = [1, 4, 6, 8]
arr = np.array(l)
print(arr)

[1 4 6 8]


In [7]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [8]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a3=np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [10]:
a4=np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
ar1=np.zeros((3,3))
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
ar2=np.ones((3,3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
ar3=np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
ar4=np.arange(1,11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
ar5=np.arange(1,11,2)
ar5

array([1, 3, 5, 7, 9])

In [16]:
ar6=np.linspace(1,10,5)
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
arr7=np.full(5,3)
arr7

array([3, 3, 3, 3, 3])

In [18]:
arr8=np.full(7,4)
arr8

array([4, 4, 4, 4, 4, 4, 4])

In [19]:
import numpy as np

In [20]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

Creating An Array

In [21]:
l=[1,4,6,8]
l

[1, 4, 6, 8]

In [22]:
l=[1,4,6,8]
print(l)

[1, 4, 6, 8]


In [23]:
import numpy as np

l = [1, 4, 6, 8]
arr = np.array(l)
print(arr)

[1 4 6 8]


In [24]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [25]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a3=np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [27]:
a4=np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
ar1=np.zeros((3,3))
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
ar2=np.ones((3,3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
ar3=np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
ar4=np.arange(1,11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
ar5=np.arange(1,11,2)
ar5

array([1, 3, 5, 7, 9])

In [33]:
ar6=np.linspace(1,10,5)
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [34]:
arr7=np.full(5,3)
arr7

array([3, 3, 3, 3, 3])

In [35]:
arr8=np.full(7,4)
arr8

array([4, 4, 4, 4, 4, 4, 4])

In [36]:
arr9=np.full((3,3),9)
arr9

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [37]:
r1=np.random.rand(3,3)
r1

array([[0.19524587, 0.68037727, 0.25694656],
       [0.46702359, 0.63074788, 0.77960465],
       [0.73436611, 0.60312345, 0.36732731]])

In [38]:
r2=np.random.rand(5)
r2

array([0.81562836, 0.22270754, 0.59034383, 0.6679394 , 0.25096284])

In [39]:
r3=np.random.randint(5)
r3

0

In [40]:
r4=np.random.randint(3,10)
r4

3

In [41]:
r5=np.random.randint(3,10,5)
r5

array([3, 3, 8, 6, 9], dtype=int32)

In [42]:
r6=np.random.randint(3,10,(3,3))
r6

array([[3, 8, 3],
       [8, 3, 6],
       [4, 7, 8]], dtype=int32)

In [43]:
r7=np.random.randint(1,10,(4,4))
r7

array([[2, 6, 9, 8],
       [3, 9, 1, 7],
       [2, 8, 8, 8],
       [9, 7, 8, 4]], dtype=int32)

Indexing of Array

In [44]:
import numpy as np

l = [1, 4, 6, 8, 5, 8, 9, 3]
arr = np.array(l)
print(arr)

[1 4 6 8 5 8 9 3]


In [45]:
print(arr[0])

1


In [46]:
print(arr[-1])

3


In [47]:
print(arr[3])

8


In [48]:
print(arr[5])

8


In [49]:
print(arr[-2])

9


In [50]:
a2=np.random.randint(1,10,(3,3))
a2

array([[5, 3, 1],
       [2, 7, 3],
       [7, 8, 4]], dtype=int32)

In [51]:
print(a2[0][1])

3


In [52]:
print(a2[2][0])

7


In [53]:
print(a2[0][0])

5


In [54]:
print(a2[0][1])

3


In [55]:
print(a2)

[[5 3 1]
 [2 7 3]
 [7 8 4]]


In [56]:
print(a2[0])

[5 3 1]


In [57]:
print(a2[1])

[2 7 3]


In [58]:
print(a2[2][1])

8


In [59]:
print(a2[1][2])

3


Slicing of Array

In [60]:
a=np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [61]:
a[0:3]

array([3, 4, 5])

In [62]:
a[-1:-5:-1]

array([9, 8, 7, 6])

In [63]:
a[2:6]

array([5, 6, 7, 8])

In [64]:
a[0:]

array([3, 4, 5, 6, 7, 8, 9])

In [65]:
a[0::1]

array([3, 4, 5, 6, 7, 8, 9])

In [66]:
a[0::2]

array([3, 5, 7, 9])

In [67]:
a[0::3]

array([3, 6, 9])

In [68]:
a[::]

array([3, 4, 5, 6, 7, 8, 9])

In [69]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3])

In [70]:
a[::-2]

array([9, 7, 5, 3])

In [71]:
a2=np.random.randint(1,10,(3,3))
a2

array([[7, 4, 9],
       [6, 1, 1],
       [2, 3, 8]], dtype=int32)

In [72]:
a2[0:2,2]

array([9, 1], dtype=int32)

In [73]:
a2[0:1,2]

array([9], dtype=int32)

In [74]:
a2[0:,1]

array([4, 1, 3], dtype=int32)

In [75]:
a2[1,0:2]

array([6, 1], dtype=int32)

In [76]:
a2[:,:]

array([[7, 4, 9],
       [6, 1, 1],
       [2, 3, 8]], dtype=int32)

In [77]:
a2[0:,1:]

array([[4, 9],
       [1, 1],
       [3, 8]], dtype=int32)

Shape,Size,and Datatype of Array

In [78]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [79]:
print(a.shape)

(7,)


In [80]:
a2

array([[7, 4, 9],
       [6, 1, 1],
       [2, 3, 8]], dtype=int32)

In [81]:
print(a2.shape)

(3, 3)


In [82]:
print(a2.size)

9


In [83]:
print(a.size)

7


In [84]:
print(a.shape)

(7,)


In [85]:
print(a.dtype)

int64


In [86]:
print(a2.dtype)

int32


mathematical operationson Array

In [87]:
a1=np.arange(11,20)
a2=np.arange(5,14)

In [88]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [89]:
a2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [90]:
a1+a2

array([16, 18, 20, 22, 24, 26, 28, 30, 32])

In [91]:
a1*a2

array([ 55,  72,  91, 112, 135, 160, 187, 216, 247])

In [92]:
a3=np.array([16,81,25,121,9])
np.sqrt(a3)

array([ 4.,  9.,  5., 11.,  3.])

In [93]:
arr9=np.full((3,3),9)
arr9

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [94]:
r1=np.random.rand(3,3)
r1

array([[0.91990195, 0.50511798, 0.60940045],
       [0.04021924, 0.08592669, 0.61055407],
       [0.80794627, 0.8376619 , 0.18590917]])

In [95]:
r2=np.random.rand(5)
r2

array([0.4928945 , 0.27521096, 0.7953865 , 0.29590132, 0.08195567])

In [96]:
r3=np.random.randint(5)
r3

3

In [97]:
r4=np.random.randint(3,10)
r4

6

In [98]:
r5=np.random.randint(3,10,5)
r5

array([4, 5, 8, 6, 9], dtype=int32)

In [99]:
r6=np.random.randint(3,10,(3,3))
r6

array([[7, 3, 6],
       [6, 6, 3],
       [9, 7, 5]], dtype=int32)

In [100]:
r7=np.random.randint(1,10,(4,4))
r7

array([[4, 5, 5, 8],
       [2, 9, 6, 5],
       [1, 1, 5, 4],
       [7, 9, 4, 4]], dtype=int32)

Indexing of Array

In [101]:
import numpy as np

l = [1, 4, 6, 8, 5, 8, 9, 3]
arr = np.array(l)
print(arr)

[1 4 6 8 5 8 9 3]


In [102]:
print(arr[0])

1


In [103]:
print(arr[-1])

3


In [104]:
print(arr[3])

8


In [105]:
print(arr[5])

8


In [106]:
print(arr[-2])

9


In [107]:
a2=np.random.randint(1,10,(3,3))
a2

array([[8, 2, 4],
       [4, 9, 1],
       [2, 4, 6]], dtype=int32)

In [108]:
print(a2[0][1])

2


In [109]:
print(a2[2][0])

2


In [110]:
print(a2[0][0])

8


In [111]:
print(a2[0][1])

2


In [112]:
print(a2)

[[8 2 4]
 [4 9 1]
 [2 4 6]]


In [113]:
print(a2[0])

[8 2 4]


In [114]:
print(a2[1])

[4 9 1]


In [115]:
print(a2[2][1])

4


In [116]:
print(a2[1][2])

1


Slicing of Array

In [117]:
a=np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [118]:
a[0:3]

array([3, 4, 5])

In [119]:
a[-1:-5:-1]

array([9, 8, 7, 6])

In [120]:
a[2:6]

array([5, 6, 7, 8])

In [121]:
a[0:]

array([3, 4, 5, 6, 7, 8, 9])

In [122]:
a[0::1]

array([3, 4, 5, 6, 7, 8, 9])

In [123]:
a[0::2]

array([3, 5, 7, 9])

In [124]:
a[0::3]

array([3, 6, 9])

In [125]:
a[::]

array([3, 4, 5, 6, 7, 8, 9])

In [126]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3])

In [127]:
a[::-2]

array([9, 7, 5, 3])

In [128]:
a2=np.random.randint(1,10,(3,3))
a2

array([[4, 3, 8],
       [6, 3, 3],
       [8, 4, 2]], dtype=int32)

In [129]:
a2[0:2,2]

array([8, 3], dtype=int32)

In [130]:
a2[0:1,2]

array([8], dtype=int32)

In [131]:
a2[0:,1]

array([3, 3, 4], dtype=int32)

In [132]:
a2[1,0:2]

array([6, 3], dtype=int32)

In [133]:
a2[:,:]

array([[4, 3, 8],
       [6, 3, 3],
       [8, 4, 2]], dtype=int32)

In [134]:
a2[0:,1:]

array([[3, 8],
       [3, 3],
       [4, 2]], dtype=int32)

Shape,Size,and Datatype of Array

In [135]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [136]:
print(a.shape)

(7,)


In [137]:
a2

array([[4, 3, 8],
       [6, 3, 3],
       [8, 4, 2]], dtype=int32)

In [138]:
print(a2.shape)

(3, 3)


In [139]:
print(a2.size)

9


In [140]:
print(a.size)

7


In [141]:
print(a.dtype)

int64


In [142]:
print(a2.dtype)

int32


mathematical operationson Array

In [143]:
a1=np.arange(11,20)
a2=np.arange(5,14)

In [144]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [145]:
a2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [146]:
a1+a2

array([16, 18, 20, 22, 24, 26, 28, 30, 32])

In [147]:
a1*a2

array([ 55,  72,  91, 112, 135, 160, 187, 216, 247])

In [148]:
a3=np.array([16,81,25,121,9])
np.sqrt(a3)

array([ 4.,  9.,  5., 11.,  3.])